
simulation:
  tick_rate_sec: 0.05
  backfill_days: 0

writers:
  - type: csv
    config:
      output_dir: "data"
      filename: "history.csv"
      allow_backfill: true
      allow_realtime: false

  - type: mqtt
    config:
      host: "localhost"
      port: 1883
      #topic_prefix: "telemetry"
      allow_backfill: false # It will ignore the 3-day backfill and only publish live data
      allow_realtime: true
      base_topic: "ev_network/Site_Melbourne_North"

assets:
  - name: "Site_Melbourne_North"
    type: "ChargingSite"
    max_queue: 3
    chargers:
      - name: "Charger_01"
        sensors:
          - name: "Grid_Voltage_AC"
            interval: 0.05
          - name: "Output_Voltage_DC"
            interval: 0.05
          - name: "Output_Current_DC"
            interval: 0.05
          - name: "Requested_Current_DC"
            interval: 0.05
          - name: "Cooling_Fan_RPM"
            interval: 0.5
          - name: "Coolant_Flow_LPM"
            interval: 0.5
          - name: "Coolant_Pressure_kPa"
            interval: 0.5
          - name: "Ambient_Temp"
            interval: 2.0
          - name: "Cabinet_Temp"
            interval: 2.0
          - name: "Cable_Connector_Temp"
            interval: 2.0
          - name: "EV_State_of_Charge"
            interval: 1.0
          - name: "Charger_State"
            interval: 1.0
          - name: "Session_Duration"
            interval: 1.0
